app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('welcome_page.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('generator/', include('generator.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

generator/urls.py
from django.urls import path

from . import views


app_name = 'generator'

urlpatterns = [
    path('schema-list/', views.SchemaListView.as_view(), name='schema-list'),
    path('schema-list/<int:pk>/create-dataset/', views.CreateDataSet.as_view(), name='create-dataset'),
    path('create-schema/', views.schema_create_view, name='schema-create'),
    path('delete-schema/<int:pk>/', views.SchemaDeleteView.as_view(), name='schema-delete'),
    path('update-schema/<int:pk>/', views.schema_update_view, name='schema-update')
]

welcome_page/urls.py
from django.urls import path

from . import views


app_name = 'welcome_page'

urlpatterns = [
    path('', views.WelcomePageView.as_view(), name='welcome-page'),
]

welcome_page/models.py
from django.db import models

# Create your models here.

welcome_page/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class WelcomePageView(TemplateView):
    template_name = 'welcome_page/index.html'

welcome_page/templates/welcome_page/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CSVFaker</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@100;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'welcome_page/style.css' %}">
</head>
<body>
<h3>Welcome to CSVFaker👋</h3>
<a href="{% url 'generator:schema-list' %}">Generate my data</a>
</body>
</html>