app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('welcome_page.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('generator/', include('generator.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

generator/urls.py
from django.urls import path

from . import views


app_name = 'generator'

urlpatterns = [
    path('schema-list/', views.SchemaListView.as_view(), name='schema-list'),
    path('schema-list/<int:pk>/create-dataset/', views.CreateDataSet.as_view(), name='create-dataset'),
    path('create-schema/', views.schema_create_view, name='schema-create'),
    path('delete-schema/<int:pk>/', views.SchemaDeleteView.as_view(), name='schema-delete'),
    path('update-schema/<int:pk>/', views.schema_update_view, name='schema-update')
]

users/urls.py
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('sign-up/', views.SignUpView.as_view(), name='sign-up'),
    path('logout/', views.login_view, name='logout'),
]

generator/models.py
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.db import models


class Schema(models.Model):
    """
    Schema model

    Attributes
    ----------
    name : str
    created : DateTime
        field that added automatically
    modified : DateTime
        field that added when model update orr retrieve
    user: ForeignKey
    """
    name = models.CharField(max_length=254)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Column(models.Model):
    """
    Column model

    Attributes
    ----------
    name : str
    type : SelectField
    order : int
    start_from : int
    to : int
    schema : ForeignKey
    """
    class Type(models.TextChoices):
        TEXT = 'TEXT', _('Text')
        FULL_NAME = 'FULL_NAME', _('Full Name')
        JOB = 'JOB', _('Job')
        EMAIL = 'EMAIL', _('Email')
        DOMAIN_NAME = 'DOMAIN_NAME', _('Domain Name')
        PHONE_NUMBER = 'PHONE_NUMBER', _('Phone Number')
        COMPANY_NAME = 'COMPANY_NAME', _('Company Name')
        INTEGER = 'INTEGER', _('Integer')
        ADDRESS = 'ADDRESS', _('Address')
        DATE = 'DATE', _('Date')

    name = models.CharField(max_length=254)
    type = models.CharField(max_length=12, choices=Type.choices)
    order = models.PositiveIntegerField()
    start_from = models.IntegerField(null=True, blank=True)
    to = models.IntegerField(null=True, blank=True)
    schema = models.ForeignKey('Schema', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class DataSet(models.Model):
    """
    DataSet model

    Attributes
    ----------
    created : DateTime
    status : ChoiceField
    file : FileField
    schame : ForeignKey
    """
    class Status(models.TextChoices):
        PROCESSING = 'PROCESSING', _('Processing')
        READY = 'READY', _('Ready')

    created = models.DateTimeField(auto_now_add=True)
    status = models.CharField(choices=Status.choices, max_length=10,  default=Status.PROCESSING)
    file = models.FileField(upload_to='data_sets/', null=True, blank=True)
    schema = models.ForeignKey('Schema', on_delete=models.CASCADE)

generator/forms.py
from django import forms
from django.forms.models import inlineformset_factory

from .models import Column, Schema


class SchemaForm(forms.ModelForm):
    """
    Form for creating Schema model with custom field
    """

    name = forms.CharField(label='',  max_length=254, widget=forms.TextInput(attrs={
        'class': 'input',
        'placeholder': 'Schema name'
    }))

    class Meta:
        model = Schema
        fields = ['name']
        exclude = ()


class ColumnForm(forms.ModelForm):
    """
    Form for creating Column model with custom fields
    """

    name = forms.CharField(label='',  max_length=254, widget=forms.TextInput(attrs={
        'class': 'input',
        'placeholder': 'Column name'
    }))
    start_from = forms.IntegerField(label='', required=False, widget=forms.NumberInput(attrs={
        'class': 'input',
        'placeholder': 'From',
    }))
    to = forms.IntegerField(label='', required=False, widget=forms.NumberInput(attrs={
        'class': 'input',
        'placeholder': 'To'
    }))
    order = forms.IntegerField(label='', widget=forms.NumberInput(attrs={
        'class': 'input',
        'placeholder': 'Order',
        'min': '1'
    }))

    class Meta:
        model = Column
        fields = ['name', 'type',  'start_from', 'to', 'order']
        exclude = ()


ColumnFormSet = inlineformset_factory(Schema, Column, form=ColumnForm, extra=1)

generator/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import TemplateView, CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Schema, Column, DataSet
from .forms import SchemaForm, ColumnFormSet
from .tasks import generate_data


class SchemaListView(LoginRequiredMixin, TemplateView):
    """
    Return Schema models list
    """

    model = Schema
    template_name = 'generator/schema_list.html'

    def get(self, request, *args, **kwargs):
        output = {
            'object_list': Schema.objects.filter(user__exact=request.user).order_by('-id')
        }
        return self.render_to_response(output)


def schema_create_view(request):
    if request.method == 'GET':
        formset = ColumnFormSet(request.GET or None)
        form = SchemaForm(request.GET or None)
    elif request.method == 'POST':
        formset = ColumnFormSet(request.POST)
        form = SchemaForm(request.POST)

        if form.is_valid() and formset.is_valid():
            schema_name = form.cleaned_data.get('name')
            schema = Schema(name=schema_name, user=request.user)
            schema.save()

            for form in formset:
                column_name = form.cleaned_data.get('name')
                column_type = form.cleaned_data.get('type')
                column_start_from = form.cleaned_data.get('start_from')
                column_to = form.cleaned_data.get('to')
                column_order = form.cleaned_data.get('order')

                column = Column(name=column_name, type=column_type, start_from=column_start_from, to=column_to,
                                schema=schema, order=column_order)
                column.save()
        else:
            return render(request, 'generator/create_schema.html', {'columns': formset, 'form': form})

        return redirect('generator:schema-list')

    return render(request, 'generator/create_schema.html', {'columns': formset, 'form': form})


def schema_update_view(request, pk):
    schema = Schema.objects.filter(pk=pk).first()
    if request.method == 'GET':
        formset = ColumnFormSet(request.GET or None, instance=schema)
        form = SchemaForm(request.GET or None, instance=schema)

    elif request.method == 'POST':
        formset = ColumnFormSet(request.POST, instance=schema)
        form = SchemaForm(request.POST, instance=schema)

        if form.is_valid() and formset.is_valid():
            schema_name = form.cleaned_data.get('name')
            schema = Schema.objects.filter(pk=pk).first()
            schema.name = schema_name
            schema.modified = timezone.now()
            schema.save()

            formset.save()
        else:
            return render(request, 'generator/create_schema.html', {'columns': formset, 'form': form})

        return redirect('generator:schema-list')

    return render(request, 'generator/create_schema.html', {'columns': formset, 'form': form})


class SchemaDeleteView(LoginRequiredMixin, DeleteView):
    model = Schema
    success_url = reverse_lazy('generator:schema-list')
    template_name = 'generator/delete_schema.html'


class CreateDataSet(LoginRequiredMixin, CreateView):
    """
    Creating DataSet model using celery task generate_data()
    """

    model = DataSet
    template_name = 'generator/create_dataset.html'
    fields = '__all__'

    def get(self, request, *args, **kwargs):
        schema = Schema.objects.filter(pk__exact=self.kwargs['pk']).first()

        return self.render_to_response(
            {'object_list': DataSet.objects.filter(
                schema__exact=schema).order_by('-id')})

    def post(self, request, *args, **kwargs):
        schema = Schema.objects.filter(pk__exact=self.kwargs['pk']).first()
        rows_num = int(request.POST.get('rows'))

        data_set = DataSet.objects.create(schema=schema)

        generate_data.delay(rows_num, [column_id.pk for column_id in schema.column_set.all()], data_set.id)
        return redirect('generator:create-dataset', pk=schema.pk)

generator/templates/generator/create_dataset.html
{% extends 'generator/wrapper.html' %}
{% load static %}

{% block title %}Create DataSet{% endblock %}
{% block extra_style %}
    <link type="text/css" rel="stylesheet" href="{% static 'generator/schema_list.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
    <div class="container__header">
        <p class="container__title">Data sets</p>
        <form method="post">
            {% csrf_token %}
            <p>Rows:</p>
            <input type="number" name="rows" placeholder="5000" required min="1">
            <button class="btn-create" type="submit">Generate</button>
        </form>
    </div>

    <table>
        <thead>
        <tr>
            <th>#</th>
            <th>Created</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for item in object_list %}
            <tr>
                <td>{{ item.pk }}</td>
                <td>{{ item.created }}</td>
                <td>
                    {% if item.status == 'READY' %}
                        <div class="status ready">
                            <p>{{ item.get_status_display }}</p>
                        </div>
                    {% else %}
                        <div class="status processing">
                            <p>{{ item.get_status_display }}</p>
                        </div>
                    {% endif %}
                </td>
                <td>
                    {% if item.file %}
                        <a class="cell-link" href="{{ item.file.url }}">Download</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}
</div>

generator/templates/generator/create_schema.html
{% extends 'generator/wrapper.html' %}
{% load static %}

{% block title %}Schema Create{% endblock %}

{% block extra_style %}
    <link type="text/css" rel="stylesheet" href="{% static 'generator/schema_create.css' %}">
{% endblock %}

{% block content %}
<div class="col-md-4">
    <form action="" method="post">
        <h3>Create new schema</h3>
        {% csrf_token %}
        {{ form.as_p }}

        <table class="table">
            {{ columns.management_form }}

            {% for form in columns.forms %}
                {% if forloop.first %}
                    <thead>
                    <tr>
                        {% for field in form.visible_fields %}
                            <th>{{ field.label|capfirst }}</th>
                        {% endfor %}
                    </tr>
                    </thead>
                {% endif %}
                <tr class="{% cycle "row1" "row2" %} formset_row">
                    {% for field in form.visible_fields %}
                        <td>
                            {# Include the hidden fields in the form #}
                            {% if forloop.first %}
                                {% for hidden in form.hidden_fields %}
                                    {{ hidden }}
                                {% endfor %}
                            {% endif %}
                            {{ field.errors.as_ul }}
                            {{ field }}
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
        <input class="save-btn" type="submit" value="Save new schema"/>
    </form>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="{% static 'generator/jquery.formset.js' %}"></script>
<script type="text/javascript">
    $('.formset_row').formset({
        addText: '+ Add column',
        deleteText: 'Delete',
        prefix: 'column_set'
    });

    function set_hidden() {
        let type_columns = document.querySelectorAll("select");
        for (let j = 0; j < type_columns.length; j++) {
            type_columns[j].onclick = function () {
                let type_columns = document.querySelectorAll("select");
                for (let i = 0; i < type_columns.length; i++) {
                    if (type_columns[i].value === 'INTEGER') {
                        const to = document.querySelector('#id_column_set-' + type_columns[i].id.split('-')[1] + '-start_from');
                        const from = document.querySelector('#id_column_set-' + type_columns[i].id.split('-')[1] + '-to');
                        to.removeAttribute('hidden');
                        from.removeAttribute('hidden');
                    } else {
                        const to = document.querySelector('#id_column_set-' + type_columns[i].id.split('-')[1] + '-start_from');
                        const from = document.querySelector('#id_column_set-' + type_columns[i].id.split('-')[1] + '-to');
                        to.setAttribute('hidden', 'True');
                        from.setAttribute('hidden', 'True');
                    }
                }
            };
        }
    }

    window.onload = function () {
        set_hidden();
    }

    let add_button = document.querySelector(".add-row");
    add_button.onclick = function () {
        set_hidden();
    };

</script>
{% endblock %}

generator/templates/generator/delete_schema.html
{% extends 'generator/wrapper.html' %}
{% load static %}

{% block title %}Delete Schema "{{ object }}"{% endblock %}

{% block extra_style %}
    <link type="text/css" rel="stylesheet" href="{% static 'generator/schema_delete.css' %}">
{% endblock %}

{% block content %}
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete <b>"{{ object }}"</b>?</p>
        <input type="submit" value="Confirm">
    </form>
{% endblock %}

generator/templates/generator/schema_list.html
{% extends 'generator/wrapper.html' %}
{% load static %}

{% block title %}Schema List{% endblock %}

{% block extra_style %}
    <link type="text/css" rel="stylesheet" href="{% static 'generator/schema_list.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="container__header">
            <p class="container__title">Data schemas</p>
            <a class="btn-create" href="{% url 'generator:schema-create' %}">+ Create New Schema</a>
        </div>

        <table>
            <thead>
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>Modified</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for item in object_list %}
                <tr>
                    <td>{{ item.pk }}</td>
                    <td><a class="cell-link" href="{% url 'generator:create-dataset' pk=item.pk %}">{{ item.name }}</a></td>
                    <td>{{ item.modified|default:"Not modified" }}</td>
                    <td>
                        <a class="cell-link" href="{% url 'generator:schema-update' pk=item.pk %}">Edit schema</a>
                        <a class="delete-link" href="{% url 'generator:schema-delete' pk=item.pk %}">Delete</a>
                    </td>
                </tr>
            {% empty %}
                <div>
                    <p>Sorry</p>
                </div>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

generator/templates/generator/wrapper.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock %}</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@100;400;700&display=swap" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{% static 'generator/style.css' %}">
    {% block extra_style %}{% endblock %}
    {% block extra_script %}{% endblock %}
</head>
<body>
<div class="header">
    <div class="left-container">
        <p class="left-container__title"><b>FakeCSV</b></p>
        <a href="{% url 'generator:schema-list' %}">Schemas</a>
    </div>
    <div class="right-container">
        <p class="right-container__user">Hello, <b>{{ user.username }}</b></p>
        <a href="{% url 'users:logout' %}">Logout</a>
    </div>
</div>
<div class="main">
    {% block content %}

    {% endblock %}
</div>
</body>
</html>