app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('welcome_page.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('generator/', include('generator.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('sign-up/', views.SignUpView.as_view(), name='sign-up'),
    path('logout/', views.login_view, name='logout'),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username',
                  'password1',
                  'password2'
                  )

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update({'class': 'login',
                                                     'placeholder': 'Username'})
        self.fields['password1'].widget.attrs.update({'class': 'confirm-password',
                                                      'placeholder': 'Password'})
        self.fields['password2'].widget.attrs.update({'class': 'confirm-password',
                                                      'placeholder': 'Confirm Password'})

users/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth import logout

from .forms import CustomUserCreationForm


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)

            return redirect('generator:schema-list')

    return render(request, 'users/login.html')


def logout_view(request):
    logout(request)

    return redirect('users:login')


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'

users/templates/users/login.html
{% extends 'users/wrapper.html' %}

{% block title %}Login{% endblock %}

{% block form %}
    <form class="form" method="POST">
        {% csrf_token %}
        <p class="form__title"><b>Login</b></p>
        <input type="text" name="username" placeholder="Username" required>
        <input type="password" name="password" placeholder="Password" required>
        <a class="form__link" href="{% url 'users:sign-up' %}">Join to FakeCSV</a>
        <div class="form__footer">
            <button class="form__submit-button" type="submit">Login</button>
        </div>
    </form>
{% endblock %}

users/templates/users/register.html
{% extends 'users/wrapper.html' %}

{% block title %}Sign Up{% endblock %}

{% block form %}
    <form class="form" method="POST">
        {% csrf_token %}
        <p class="form__title"><b>Sign Up</b></p>
        <input id="id_username" type="text" name="username" placeholder="Username" required>
        <input id="id_password1" type="password" name="password1" placeholder="Password" required>
        <input id="id_password2" type="password" name="password2" placeholder="Confirm Password" required>
        <a class="form__link" href="{% url 'users:login' %}">Already have an account?</a>
        <div class="form__footer">
            <button class="form__submit-button" type="submit">Register</button>
        </div>
    </form>
{% endblock %}

users/templates/users/wrapper.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock %}</title
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@100;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'users/auth.css' %}">
</head>
<body>
<div class="main-container">
    <div class="form-wrapper">
        {% block form %}{% endblock %}
    </div>
</div>
</body>
</html>